ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  audience: "http://0.0.0.0:8080/photos"
  realm: "Photo Access"
  issuer: "http://0.0.0.0:8080/"
  secret:  ${?SECRET}

db:
  driver: "org.h2.Driver"
  url: "jdbc:h2:file:./data/appdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
  user: "admin"
  password: ""
